### PR TITLE
Added JaJP translation files

### PR DESCRIPTION
**Pull request by yutarour**
Hi hope everyone at Argonaut Industries is excited about splatoon3.

With a new Splatoon game comes another bot. With the bot comes translating files; so here are the jaJP translation files for splatoon 2 and 3 spyke bot. There is one problem though, it is the fact that there is so much garbage unicode in there that I don't know what to do. Let me know if I can do something. 

Edit:
forgot to mention there were a ton of \n in the splatoon 3 files in the English translations that were removed for splatoon 2. I also removed those (if you were wondering about the edits in the English version)

Thanks, 
yutarour

### CODE REVIEW

**Comment by Starwort** [comment]
Pulling this in the way I want seems to be complicated; I'll merge the changes manually (not the entirety of the PR), and then close this PR. Thank you for your submission!

**Comment by yutarour** [comment]
Sounds good

**Comment by Starwort** [comment]
@yutarour I pinged you on discord, but I don't think you noticed; was the decision to not translate command names intentional? Surely it would make more sense to use, e.g. `サーモン２` rather than `salmon2`?

**Comment by Starwort** [comment]
Closed by 048b6b. Please reopen if you think I've missed something

**Pull request closed without merging**
